name: Tweetbot

on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Run Bot
        run: npm i && node index.js
        env:
          DB_HOST: ${{secrets.ENV.DB_HOST}}
          DB_USER: ${{secrets.ENV.DB_USER}}
          DB_PASS: ${{secrets.ENV.DB_PASS}}
          CONSUMER_KEY: ${{secrets.ENV.CONSUMER_KEY}}
          CONSUMER_SECRET: ${{secrets.ENV.CONSUMER_SECRET}}
          BEARER_TK: ${{secrets.ENV.BEARER_TK}}
          ACCESS_TOKEN: ${{secrets.ENV.ACCESS_TOKEN}}
          ACCESS_TOKEN_SECRET: ${{secrets.ENV.ACCESS_TOKEN_SECRET}}
