name: Tweetbot

on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Run Bot
        run: npm i && node index.js
        env:
          BOT_GITHUB_TOKEN: ${{ secrets.ENV }}
