name: Tweetbot

on:
  schedule:
    - cron: '* * * * *' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install package and run the script
        run: npm i && node index.js
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{secrets.DB_USER}}
          DB_PASS: ${{secrets.DB_PASS}}
          CONSUMER_KEY: ${{secrets.CONSUMER_KEY}}
          CONSUMER_SECRET: ${{secrets.CONSUMER_SECRET}}
          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
          ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
